/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhatWeAcceptRouteImport } from './routes/what-we-accept'
import { Route as SustainabilityRouteImport } from './routes/sustainability'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SchedulePickupRouteImport } from './routes/schedule-pickup'
import { Route as EventsRouteImport } from './routes/events'
import { Route as EventRegistrationRouteImport } from './routes/event-registration'
import { Route as CorporateRouteImport } from './routes/corporate'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConferencesRouteImport } from './routes/conferences'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const WhatWeAcceptRoute = WhatWeAcceptRouteImport.update({
  id: '/what-we-accept',
  path: '/what-we-accept',
  getParentRoute: () => rootRouteImport,
} as any)
const SustainabilityRoute = SustainabilityRouteImport.update({
  id: '/sustainability',
  path: '/sustainability',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulePickupRoute = SchedulePickupRouteImport.update({
  id: '/schedule-pickup',
  path: '/schedule-pickup',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const EventRegistrationRoute = EventRegistrationRouteImport.update({
  id: '/event-registration',
  path: '/event-registration',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateRoute = CorporateRouteImport.update({
  id: '/corporate',
  path: '/corporate',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConferencesRoute = ConferencesRouteImport.update({
  id: '/conferences',
  path: '/conferences',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/case-studies': typeof CaseStudiesRoute
  '/conferences': typeof ConferencesRoute
  '/contact': typeof ContactRoute
  '/corporate': typeof CorporateRoute
  '/event-registration': typeof EventRegistrationRoute
  '/events': typeof EventsRoute
  '/schedule-pickup': typeof SchedulePickupRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sustainability': typeof SustainabilityRoute
  '/what-we-accept': typeof WhatWeAcceptRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/case-studies': typeof CaseStudiesRoute
  '/conferences': typeof ConferencesRoute
  '/contact': typeof ContactRoute
  '/corporate': typeof CorporateRoute
  '/event-registration': typeof EventRegistrationRoute
  '/events': typeof EventsRoute
  '/schedule-pickup': typeof SchedulePickupRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sustainability': typeof SustainabilityRoute
  '/what-we-accept': typeof WhatWeAcceptRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/case-studies': typeof CaseStudiesRoute
  '/conferences': typeof ConferencesRoute
  '/contact': typeof ContactRoute
  '/corporate': typeof CorporateRoute
  '/event-registration': typeof EventRegistrationRoute
  '/events': typeof EventsRoute
  '/schedule-pickup': typeof SchedulePickupRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sustainability': typeof SustainabilityRoute
  '/what-we-accept': typeof WhatWeAcceptRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/case-studies'
    | '/conferences'
    | '/contact'
    | '/corporate'
    | '/event-registration'
    | '/events'
    | '/schedule-pickup'
    | '/services'
    | '/sitemap.xml'
    | '/sustainability'
    | '/what-we-accept'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/case-studies'
    | '/conferences'
    | '/contact'
    | '/corporate'
    | '/event-registration'
    | '/events'
    | '/schedule-pickup'
    | '/services'
    | '/sitemap.xml'
    | '/sustainability'
    | '/what-we-accept'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/case-studies'
    | '/conferences'
    | '/contact'
    | '/corporate'
    | '/event-registration'
    | '/events'
    | '/schedule-pickup'
    | '/services'
    | '/sitemap.xml'
    | '/sustainability'
    | '/what-we-accept'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  CaseStudiesRoute: typeof CaseStudiesRoute
  ConferencesRoute: typeof ConferencesRoute
  ContactRoute: typeof ContactRoute
  CorporateRoute: typeof CorporateRoute
  EventRegistrationRoute: typeof EventRegistrationRoute
  EventsRoute: typeof EventsRoute
  SchedulePickupRoute: typeof SchedulePickupRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SustainabilityRoute: typeof SustainabilityRoute
  WhatWeAcceptRoute: typeof WhatWeAcceptRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/what-we-accept': {
      id: '/what-we-accept'
      path: '/what-we-accept'
      fullPath: '/what-we-accept'
      preLoaderRoute: typeof WhatWeAcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sustainability': {
      id: '/sustainability'
      path: '/sustainability'
      fullPath: '/sustainability'
      preLoaderRoute: typeof SustainabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule-pickup': {
      id: '/schedule-pickup'
      path: '/schedule-pickup'
      fullPath: '/schedule-pickup'
      preLoaderRoute: typeof SchedulePickupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event-registration': {
      id: '/event-registration'
      path: '/event-registration'
      fullPath: '/event-registration'
      preLoaderRoute: typeof EventRegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate': {
      id: '/corporate'
      path: '/corporate'
      fullPath: '/corporate'
      preLoaderRoute: typeof CorporateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conferences': {
      id: '/conferences'
      path: '/conferences'
      fullPath: '/conferences'
      preLoaderRoute: typeof ConferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  CaseStudiesRoute: CaseStudiesRoute,
  ConferencesRoute: ConferencesRoute,
  ContactRoute: ContactRoute,
  CorporateRoute: CorporateRoute,
  EventRegistrationRoute: EventRegistrationRoute,
  EventsRoute: EventsRoute,
  SchedulePickupRoute: SchedulePickupRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SustainabilityRoute: SustainabilityRoute,
  WhatWeAcceptRoute: WhatWeAcceptRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
